spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/quarry
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: health