spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/quarry
    username: dev
    password: dev
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: health
quarry:
  import:
    username: ${QUARRY_IMPORT_USERNAME:AnishGiri}
    max: 20